### ISSUE TITLE
v0.5.9.5-ls37 fails to start

### ISSUE THREAD

**Issue by cwhits** [linuxserver/docker-mylar3#16]
## Expected Behavior
Container should start

## Current Behavior
Container fails to start

## Steps to Reproduce
1. Pull v0.5.9.5-ls37 or `latest`
2. Start container
3. docker logs mylar

## Environment
**OS:** Ubuntu (docker)
**CPU architecture:** x86_64
**How docker service was installed:**
apt install docker

## Command used to create docker container (run/create/compose/screenshot)
```
  mylar:
    container_name: "mylar"
    image: "ghcr.io/linuxserver/mylar3"
    volumes:
      - ${DOCKER_HOME}/mylar:/config
      - ${DOCKER_HOME}/mylar/99-my-script:/etc/cont-init.d/99-my-script
      - /media/storage/downloads:/downloads
      - /media/storage/comics:/comics
    restart: always
    ports:
      - 8090:8090
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
```

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Mylar3: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EWQADB5AMVRFU

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] 99-my-script: executing... 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/2) Installing unzip (6.0-r9)
(2/2) Installing zip (3.0-r9)
Executing busybox-1.32.1-r6.trigger
OK: 127 MiB in 81 packages
[cont-init.d] 99-my-script: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar3/mylar/__init__.py", line 39, in <module>
    import cherrypy
  File "/usr/lib/python3.8/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/lib/python3.8/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/lib/python3.8/site-packages/jaraco/collections.py", line 10, in <module>
    import jaraco.text
  File "/usr/lib/python3.8/site-packages/jaraco/text/__init__.py", line 228, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
AttributeError: 'PosixPath' object has no attribute 'read_text'
```
